#!/usr/bin/env python3
"""Generate VitePress markdown pages from the JSON produced by
extract_game_data.py (run that first).

Fully generated pages (overwritten on every run):
  adventurers/stats-comparison.md, adventurers/doctrines.md,
  adventurers/traits.md, items/weapons.md, items/armors.md,
  items/accessories.md, items/recipes.md, enemies/bestiary.md,
  changelog.md

Marker pages (hand-written prose preserved; data blocks refreshed):
  dungeons/dungeons.md, dungeons/raids.md, mechanics/status-effects.md
  -> content between `<!-- BEGIN GENERATED DATA -->` and
     `<!-- END GENERATED DATA -->` is replaced.

Stdlib-only. See docs/scripts.md.

Usage:
  python scripts/igmplus_wiki/generate_pages.py [--repo ROOT] [--wiki DIR]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_REPO = SCRIPT_DIR.parents[1]

BEGIN = "<!-- BEGIN GENERATED DATA -->"
END = "<!-- END GENERATED DATA -->"
BANNER = "<!-- AUTO-GENERATED by scripts/igmplus_wiki/generate_pages.py. Do not edit by hand; run `npm run generate`. -->"

STAT_LABELS = {
    "baseMaxHp": "HP",
    "baseConstitution": "CON",
    "baseIntelligence": "INT",
    "baseDexterity": "DEX",
    "baseDefense": "DEF",
    "baseMagicDefense": "MDEF",
    "baseLifesteal": "Lifesteal",
    "constitution": "CON",
    "intelligence": "INT",
    "dexterity": "DEX",
    "strength": "STR",
    "maxHp": "Max HP",
    "defense": "DEF",
    "magicDefense": "MDEF",
    "attackSpeed": "Attack Speed",
    "critChance": "Crit Chance",
    "criticalChance": "Crit Chance",
    "critDamage": "Crit Damage",
    "criticalDamage": "Crit Damage",
    "counterattack": "Counterattack",
    "dodgeChance": "Dodge",
    "flatDodgeChance": "Dodge",
    "lifesteal": "Lifesteal",
    "hp": "HP",
    "regeneration": "Regen",
    "threat": "Threat",
    "immunityToStatus": "Status Immunity",
    "bonusExperience": "Bonus EXP",
    "damageDealtModifier": "Damage Dealt",
    "damageTakenModifier": "Damage Taken",
    "normalAttackAmpModifier": "Normal Atk Amp",
    "skillAmpModifier": "Skill Amp",
    "retaliationPhysicalDamage": "Physical Retaliation",
    "retaliationMagicalDamage": "Magic Retaliation",
    "healingModifier": "Healing Bonus",
}

PERCENT_STATS = {
    "critChance",
    "criticalChance",
    "critDamage",
    "criticalDamage",
    "counterattack",
    "dodgeChance",
    "flatDodgeChance",
    "immunityToStatus",
    "damageDealtModifier",
    "damageTakenModifier",
    "normalAttackAmpModifier",
    "skillAmpModifier",
    "healingModifier",
}


# --------------------------------------------------------------------------
# IO helpers
# --------------------------------------------------------------------------

def load(data_dir: Path, name: str):
    return json.loads((data_dir / name).read_text(encoding="utf-8"))


def md_cell(text) -> str:
    """Make a value safe inside a markdown table cell."""
    if text is None:
        return "—"
    s = str(text)
    s = s.replace("|", "\\|").replace("\n", " ").strip()
    return s or "—"


def table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(md_cell(c) for c in row) + " |")
    return "\n".join(out)


def write_page(wiki: Path, rel: str, body: str, generated: bool = True) -> None:
    target = wiki / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    prefix = (BANNER + "\n") if generated else ""
    target.write_text(prefix + body.rstrip() + "\n", encoding="utf-8")
    print(f"  page {rel}")


def write_marker_block(wiki: Path, rel: str, header: str, block: str) -> None:
    """Create the page with header + markers, or refresh the marker block."""
    target = wiki / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    fresh = f"{header.rstrip()}\n\n{BEGIN}\n{block.rstrip()}\n{END}\n"
    if target.is_file():
        text = target.read_text(encoding="utf-8")
        bi, ei = text.find(BEGIN), text.find(END)
        if bi == -1 or ei == -1 or ei < bi:
            print(f"  error: {rel} is missing marker comments", file=sys.stderr)
            raise SystemExit(2)
        text = text[: bi + len(BEGIN)] + "\n" + block.rstrip() + "\n" + text[ei:]
        target.write_text(text, encoding="utf-8")
    else:
        target.write_text(fresh, encoding="utf-8")
    print(f"  page {rel} (markers)")


class Assets:
    """Resolves sprite resource names to /images/<file> URLs."""

    def __init__(self, data_dir: Path):
        self.files: dict[str, str] = {}
        manifest_path = data_dir / "sprites_manifest.json"
        if not manifest_path.is_file():
            return  # export_sprites.py has not run yet; render without images
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.files = {
            name: entry["file"] for name, entry in manifest["exported"].items()
        }

    def img(self, sprite: str | None, size: int = 28) -> str:
        if not sprite or sprite not in self.files:
            return "—"
        return (
            f'<img :src="$withBase(\'/images/{self.files[sprite]}\')" class="sprite" '
            f'alt="{sprite}" width="{size}" height="{size}">'
        )


def fmt_stats(stats: dict) -> str:
    parts = []
    for key, val in (stats or {}).items():
        label = STAT_LABELS.get(key, key)
        if key in PERCENT_STATS and isinstance(val, (int, float)):
            pct = val * 100 if abs(val) <= 1.0 else val
            sign = "+" if pct > 0 else ""
            parts.append(f"{label} {sign}{pct:g}%")
        elif isinstance(val, (int, float)):
            sign = "+" if val > 0 and key not in ("baseMaxHp", "maxHp", "hp") else ""
            parts.append(f"{label} {sign}{val:g}" if isinstance(val, float) else f"{label} {sign}{val}")
        else:
            parts.append(f"{label} {val}")
    return " · ".join(parts) or "—"


# --------------------------------------------------------------------------
# Adventurers
# --------------------------------------------------------------------------

def build_stats_comparison(ctx) -> str:
    adv = ctx["adventurers"]
    skills = {s["key"]: s["name"] for s in ctx["skills"]}
    tiers = adv["tiers"]
    rows_all = []
    lines = [
        "# Adventurer Stats Comparison",
        "",
        "Base statistics at level 1 for every adventurer class across all promotion tiers.",
        "Compare base health, primary attributes, defenses, weapon affinities, and skill loadouts.",
        "",
    ]
    unit_by_key = {u["key"]: u for u in adv["units"]}
    for tier_key in sorted(tiers, key=int):
        lines.append(f"## Tier {tier_key}")
        lines.append("")
        rows = []
        for key in tiers[tier_key]:
            u = unit_by_key.get(key)
            if u is None or u.get("missing"):
                continue
            stats = u.get("stats") or {}
            weapon_str = u.get("weapon_type") and u["weapon_type"].replace("type_", "").capitalize() or "—"
            next_cls_str = ", ".join(unit_by_key.get(nc, {}).get("name", nc) for nc in u.get("next_classes") or []) or "—"
            rows.append(
                [
                    f"**{u.get('name') or key}**",
                    Assets_img(ctx, u.get("sprite")),
                    stats.get("baseMaxHp", "—"),
                    stats.get("baseConstitution", "—"),
                    stats.get("baseIntelligence", "—"),
                    stats.get("baseDexterity", "—"),
                    stats.get("baseDefense", "—"),
                    stats.get("baseMagicDefense", "—"),
                    u.get("max_level", "—"),
                    weapon_str,
                    skills.get(u.get("active_skill") or "", "—"),
                    skills.get(u.get("passive_skill") or "", "—"),
                    next_cls_str,
                ]
            )
        lines.append(
            table(
                [
                    "Class", "Sprite", "HP", "CON", "INT", "DEX", "DEF", "MDEF",
                    "Cap", "Weapon", "Active Skill", "Passive Skill", "Promotes To",
                ],
                rows,
            )
        )
        lines.append("")
        rows_all.extend(rows)
    return "\n".join(lines)


def Assets_img(ctx, sprite, size: int = 28):
    return ctx["assets"].img(sprite, size)


def build_doctrines(ctx) -> str:
    abilities = {a["key"]: a for a in ctx["doctrine_abilities"]}
    lines = [
        "# Doctrines",
        "",
        "Doctrines offer specialized passives, attribute increases, and unique rule-breaking mechanics",
        "to customize and empower your adventurers. Each doctrine contains 7 ability nodes",
        "upgraded using doctrine points.",
        "",
    ]
    for d in ctx["doctrines"]:
        if d["key"] == "EmptyDoctrine":
            continue
        lines.append(f"## {d['name']}")
        lines.append("")
        lines.append(Assets_img(ctx, d.get("sprite"), 48))
        lines.append("")
        if d.get("description"):
            lines.append(d["description"])
            lines.append("")
        rows = []
        for ab_key in d["abilities"]:
            ab = abilities.get(ab_key)
            if not ab:
                rows.append([f"`{ab_key}`", "—", "—", "—", "—"])
                continue
            rows.append(
                [
                    Assets_img(ctx, ab.get("sprite"), 20) + " " + ab["name"],
                    ab["cost"],
                    ab["increase_per_level"],
                    ab["max_level"],
                    ab.get("description") or "—",
                ]
            )
        lines.append(
            table(["Ability", "Cost/lvl", "+Per Point", "Max Lvl", "Effect"], rows)
        )
        lines.append("")
    return "\n".join(lines)


def build_traits(ctx) -> str:
    lines = [
        "# Traits",
        "",
        "Traits are innate character quirks rolled on recruitment (common/rare).",
        "`+` traits are the permanent amplified forms obtained through Evolution",
        "Vial upgrades (Evo-24 style).",
        "",
    ]
    rows = []
    for t in ctx["traits"]:
        rows.append(
            [
                Assets_img(ctx, None),
                t["name"] + (" **(+)**" if t.get("plus") else ""),
                t.get("description") or "—",
            ]
        )
    lines.append(table(["", "Trait", "Effect"], rows))
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Items
# --------------------------------------------------------------------------

WEAPON_CATS = {"Sword", "Axe", "Bow", "Staff", "Dagger", "Weapon"}
ARMOR_CATS = {"LightArmor", "MediumArmor", "HeavyArmor", "Armor"}
ACC_CATS = {"Accessory"}
CONSUMABLE_CATS = {"Food", "Potion", "Consumable", "Egg", "Upgrade"}

INTERESTING_OVERRIDES = (
    "damageDelta", "damageDescription", "isMagic", "isRanged",
    "getSecondsToCraft", "onUse", "isConsumable",
)


def item_notes(item: dict) -> str:
    parts = []
    overrides = item.get("overrides") or {}
    if overrides.get("isMagic") == "true":
        parts.append("Magical Damage")
    if overrides.get("isRanged") == "true":
        parts.append("Ranged Attack")
    if overrides.get("damageDelta"):
        try:
            delta = float(overrides["damageDelta"])
            parts.append(f"Variance ±{int(delta * 100)}%")
        except ValueError:
            pass
    if overrides.get("alwaysHits") == "true":
        parts.append("Always Hits")
    if overrides.get("initiative") == "true":
        parts.append("Initiative")
    flags = item.get("flags") or {}
    if flags.get("isRareDrop"):
        parts.append("Rare Drop")
    if flags.get("isNotSellable"):
        parts.append("Cannot Sell")
    if flags.get("uniqueOrigin"):
        parts.append(f"Unique: {flags['uniqueOrigin']}")
    return "<br>".join(parts) or "—"


def build_items_table(ctx, categories: set[str]) -> str:
    rows = []
    for it in ctx["items"]["items"]:
        if it.get("category") not in categories:
            continue
        rows.append(
            [
                ctx["assets"].img(it.get("sprite"), 56),
                f"**{it['name']}**",
                it.get("category") or "—",
                it.get("price") if it.get("price") is not None else "—",
                it.get("rarity") if it.get("rarity") is not None else 0,
                fmt_stats(it.get("stats") or {}),
                item_notes(it),
            ]
        )
    rows.sort(key=lambda r: (r[3] if isinstance(r[3], (int, float)) else 0))
    return table(
        ["", "Name", "Type", "Price", "Rarity", "Stats", "Notes"], rows
    )


def build_items_page(ctx, title: str, intro: str, component: str,
                     categories: set[str]) -> str:
    return "\n".join(
        [
            f"# {title}",
            "",
            intro,
            "",
            f'<{component} />',
            "",
            "::: details Complete equipment table",
            "",
            build_items_table(ctx, categories),
            "",
            ":::",
            "",
        ]
    )


def build_recipes(ctx) -> str:
    items = ctx["items"]["items"]
    by_key = {i["key"]: i for i in items}
    lines = [
        "# Recipes",
        "",
        "Workshop crafting recipes. Every recipe consumes the listed ingredients",
        "to produce equipment, materials, or upgraded items.",
        "",
        "::: tip Workshop Upgrades",
        "Crafting speed increases with each workshop level, reducing total craft times.",
        ":::",
        "",
        "## Recipes",
        "",
    ]
    rows = []
    for r in ctx["recipes"]:
        out_item = by_key.get(r["output_item"])
        name = out_item["name"] if out_item else r["output_item"]
        ing_parts = []
        for i in r["ingredients"]:
            it_obj = by_key.get(i["item"], {})
            it_name = it_obj.get("name", i["item"])
            it_sprite = it_obj.get("sprite")
            img_tag = ctx["assets"].img(it_sprite, 28) if it_sprite else ""
            ing_parts.append(
                f'<span class="recipe-ingredient-chip">{img_tag}<span class="ing-name">{it_name}</span><span class="ing-qty">×{i["qty"]}</span></span>'
            )
        ing = f'<div class="recipe-ingredients-wrap">{"".join(ing_parts)}</div>'
        cat_badge = f'<span class="recipe-type-badge">{out_item.get("category")}</span>' if out_item and out_item.get("category") else ''
        output_cell = (
            f'<div class="recipe-output-cell">'
            f'{ctx["assets"].img(out_item.get("sprite") if out_item else None, 52)}'
            f'<div class="recipe-output-info"><strong>{name}</strong>{cat_badge}</div>'
            f'</div>'
        )
        price_val = out_item.get("price") if out_item else None
        price_cell = f'<span class="recipe-price">🪙 {price_val}</span>' if price_val is not None else "—"
        rows.append(
            [
                output_cell,
                '<div class="recipe-arrow">➔</div>',
                ing,
                price_cell,
            ]
        )
    lines.append(table(["Output", "", "Ingredients", "Price"], rows))
    lines += ["", "## Materials", "",
              "Base crafting materials (items without equipment stats).", ""]
    mrows = []
    for it in items:
        if it.get("category") is not None:
            continue
        mrows.append(
            [
                ctx["assets"].img(it.get("sprite"), 48),
                it["name"],
                it.get("price") if it.get("price") is not None else "—",
            ]
        )
    mrows.sort(key=lambda r: (r[2] if isinstance(r[2], (int, float)) else 0))
    lines.append(table(["", "Material", "Price"], mrows))
    lines += ["", "## Consumables, Food & Upgrades", ""]
    crows = []
    for it in items:
        if it.get("category") not in CONSUMABLE_CATS:
            continue
        crows.append(
            [
                ctx["assets"].img(it.get("sprite"), 48),
                f"**{it['name']}**",
                it.get("category"),
                it.get("price") if it.get("price") is not None else "—",
                item_notes(it),
            ]
        )
    crows.sort(key=lambda r: (r[2] or "", r[1]))
    lines.append(table(["", "Name", "Type", "Price", "Notes"], crows))
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Dungeons & Raids
# --------------------------------------------------------------------------

TYPE_LABELS = {0: "Dungeon", 1: "Raid", 2: "Epic Raid"}


def place_section(ctx, pl: dict) -> list[str]:
    lines = [f"## {pl['name']}", ""]
    sprite = pl.get("summary_sprite") or pl.get("detail_sprite")
    if sprite:
        lines += [ctx["assets"].img(sprite, 96), ""]
    meta = []
    if pl.get("area_type") is not None:
        meta.append(f"**Type:** {TYPE_LABELS.get(pl['area_type'], pl['area_type'])}")
    if pl.get("level") is not None:
        meta.append(f"**Req. level:** {pl['level']}")
    if pl.get("encounter_chance_permille") is not None and pl.get("encounter_chance_permille") > 0:
        meta.append(
            f"**Encounter chance:** {pl['encounter_chance_permille'] / 10:.1f}% per room"
        )
    if meta:
        lines += [" · ".join(meta), ""]

    all_enemies = pl.get("enemies") or []
    # Filter out TutorialWolf if present
    all_enemies = [e for e in all_enemies if e.get("key") != "TutorialWolf"]

    if all_enemies:
        rows = []
        def sort_key(e):
            cp = e.get("chance_permille")
            if cp is not None:
                return (0, -cp)
            unit = ctx["enemy_by_key"].get(e["key"])
            is_boss = bool(unit and unit.get("is_boss"))
            return (1 if is_boss else 2, 0)

        for e in sorted(all_enemies, key=sort_key):
            unit = ctx["enemy_by_key"].get(e["key"])
            name = unit["name"] if unit else e["key"]
            is_boss = bool(unit and unit.get("is_boss"))
            if e.get("chance_permille") is not None:
                rate = f"{e['chance_permille'] / 10:.1f}%"
                role = "**Boss**" if is_boss else "Regular"
            else:
                rate = "Event / Scripted"
                role = "**Boss**" if is_boss else "Special Spawn"

            rows.append(
                [
                    ctx["assets"].img(unit.get("sprite") if unit else None, 36),
                    f"**{name}**",
                    rate,
                    role,
                ]
            )
        lines += [table(["", "Enemy", "Share of Encounters", "Role / Type"], rows), ""]

    if pl.get("items_mentioned"):
        lines += [
            "<details><summary>Loot & item references</summary>",
            "",
            ", ".join(pl["items_mentioned"]),
            "",
            "</details>",
            "",
        ]
    return lines


def build_places(ctx, wanted_types: set, title: str, intro: str,
                 *, full: bool = True) -> str:
    places = [
        p
        for p in ctx["places"]
        if p.get("area_type") in wanted_types
        or (None in wanted_types and p.get("area_type") is None)
    ]
    places.sort(key=lambda p: (p.get("area_type") or 9, p["name"]))
    body: list[str] = []
    for pl in places:
        body += place_section(ctx, pl)
    if not full:
        return "\n".join(body)
    return "\n".join([f"# {title}", "", intro, ""] + body)


# --------------------------------------------------------------------------
# Bestiary
# --------------------------------------------------------------------------

def fmt_damage(expr: str | None) -> str:
    if not expr:
        return "—"
    expr = expr.strip().rstrip("{}").strip().strip("`")
    if re.fullmatch(r"-?\d+", expr):
        return expr
    return expr if len(expr) <= 60 else "…"


def build_bestiary(ctx) -> str:
    lines = [
        "# Bestiary",
        "",
        "Complete catalog of all enemies with base statistics, damage ranges, and item drop rates.",
        "Boss encounters are marked with 👑 and special independent bonus drops are marked with ★.",
        "",
    ]
    rows = []
    for e in sorted(ctx["enemies"], key=lambda x: x["name"] or x["key"]):
        drops = []
        for d in e.get("drops") or []:
            drops.append(
                f"{ctx['item_names'].get(d['item'], d['item'])} ×{d['qty']} "
                f"({d['weight'] / 10:.1f}%)"
            )
        for d in e.get("independent_drops") or []:
            drops.append(
                f"★ {ctx['item_names'].get(d['item'], d['item'])} ×{d['qty']} "
                f"({d['chance'] * 100:g}% independent)"
            )
        stats = e.get("stats") or {}
        rows.append(
            [
                ctx["assets"].img(e.get("sprite"), 28),
                f"**{e['name']}**" + (" 👑" if e.get("is_boss") else ""),
                stats.get("baseMaxHp", "—"),
                stats.get("baseConstitution", "—"),
                stats.get("baseIntelligence", "—"),
                stats.get("baseDexterity", "—"),
                stats.get("baseDefense", "—"),
                stats.get("baseMagicDefense", "—"),
                f"{fmt_damage(e.get('min_damage'))} – {fmt_damage(e.get('max_damage'))}",
                e.get("exp_given") if e.get("exp_given") is not None else "—",
                "<br>".join(drops) or "—",
            ]
        )
    lines.append(
        table(
            ["", "Enemy", "HP", "CON", "INT", "DEX", "DEF", "MDEF",
             "Damage", "EXP", "Drops"],
            rows,
        )
    )
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Changelog
# --------------------------------------------------------------------------

def build_changelog(ctx) -> str:
    lines = [
        "# Changelog",
        "",
        "Every mod release, newest first (extracted from `ModChangelog*.kt`).",
        "",
    ]
    for v in ctx["changelog"]:
        date = f" — {v['date']}" if v.get("date") else ""
        lines += [f"## v{v['version']}{date}", ""]
        for group in v.get("groups") or []:
            if not group:
                continue
            head = group[0]
            rest = group[1:]
            if head.endswith(":"):
                lines += [f"**{head}**", ""]
                if rest:
                    lines += [f"- {pt}" for pt in rest] + [""]
            else:
                lines += [f"- {pt}" for pt in group] + [""]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Status effects (marker block for mechanics/status-effects.md)
# --------------------------------------------------------------------------

def build_status_effect_block(ctx) -> str:
    rows = []
    for s in ctx["status_effects"]:
        rows.append(
            [
                ctx["assets"].img(s.get("sprite"), 20),
                f"**{s['name']}**",
                "Yes" if s.get("negative") else "No",
                s.get("description") or "—",
            ]
        )
    intro = (
        "All status effects registered in `StatusEffectType.kt`. *Negative* marks "
        "debuffs (cleansable by virtue-dispel style effects unless flagged "
        "otherwise in code)."
    )
    return "\n".join(
        [intro, "", table(["", "Effect", "Negative", "Description"], rows)]
    )


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", type=Path, default=DEFAULT_REPO)
    ap.add_argument("--wiki", type=Path, default=None,
                    help="wiki dir (default <repo>/igmplus_wiki)")
    args = ap.parse_args(argv)
    repo = args.repo.resolve()
    wiki = (args.wiki or repo / "igmplus_wiki").resolve()
    data_dir = wiki / "data"

    required = ["items.json", "units_adventurers.json", "places.json"]
    missing = [n for n in required if not (data_dir / n).is_file()]
    if missing:
        print(
            f"error: missing {missing} in {data_dir}; run extract_game_data.py first",
            file=sys.stderr,
        )
        return 1

    print(f"generating pages in {wiki}")
    ctx = {
        "assets": Assets(data_dir),
        "skills": load(data_dir, "skills.json"),
        "traits": load(data_dir, "traits.json"),
        "status_effects": load(data_dir, "status_effects.json"),
        "doctrine_abilities": load(data_dir, "doctrine_abilities.json"),
        "doctrines": load(data_dir, "doctrines.json"),
        "adventurers": load(data_dir, "units_adventurers.json"),
        "enemies": load(data_dir, "units_enemies.json"),
        "items": load(data_dir, "items.json"),
        "recipes": load(data_dir, "recipes.json"),
        "places": load(data_dir, "places.json"),
        "changelog": load(data_dir, "changelog.json"),
    }
    ctx["enemy_by_key"] = {e["key"]: e for e in ctx["enemies"]}
    ctx["item_names"] = {i["key"]: i["name"] for i in ctx["items"]["items"]}

    # -- fully generated pages -------------------------------------------
    write_page(wiki, "adventurers/stats-comparison.md",
               build_stats_comparison(ctx))
    write_page(wiki, "adventurers/doctrines.md", build_doctrines(ctx))
    write_page(wiki, "adventurers/traits.md", build_traits(ctx))
    write_page(
        wiki, "items/weapons.md",
        build_items_page(
            ctx, "Weapons",
            "Swords, axes, bows, staves and daggers. Use the filters to narrow by "
            "type, rarity or stat; the collapsible table below mirrors the same data.",
            "ItemFilter category=\"weapon\"",
            WEAPON_CATS,
        ),
    )
    write_page(
        wiki, "items/armors.md",
        build_items_page(
            ctx, "Armors",
            "Light, medium and heavy armor sets with their defensive stats.",
            "ItemFilter category=\"armor\"",
            ARMOR_CATS,
        ),
    )
    write_page(
        wiki, "items/accessories.md",
        build_items_page(
            ctx, "Accessories",
            "Rings, capes, amulets and trinkets.",
            "ItemFilter category=\"accessory\"",
            ACC_CATS,
        ),
    )
    write_page(wiki, "items/recipes.md", build_recipes(ctx))
    write_page(wiki, "enemies/bestiary.md", build_bestiary(ctx))
    write_page(wiki, "changelog.md", build_changelog(ctx))

    # -- marker pages (hand-written prose preserved) ---------------------
    write_marker_block(
        wiki, "dungeons/dungeons.md", "# Dungeons",
        build_places(ctx, {0, None}, "# Dungeons", "", full=False),
    )
    write_marker_block(
        wiki, "dungeons/raids.md", "# Raids",
        build_places(ctx, {1, 2}, "# Raids", "", full=False),
    )
    write_marker_block(
        wiki, "mechanics/status-effects.md", "# Status Effects",
        build_status_effect_block(ctx),
    )
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

